exclude = [
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "__pypackages__",
    "__pycache__",
]

line-length = 120
indent-width = 4
target-version = "py310"

[lint]
select = ["ALL"]
ignore = [
    "D400",  # First line should end with a period
    "D415",  # First line should end with a period, question mark, or exclamation point
    "ANN204", # Missing return type annotation for special method __init__
    "S311",  # Standard pseudo-random generators are not suitable for cryptographic purposes
    "EM101",  # Exception must not use a string literal, assign to variable first
    "S101",  # Use of `assert` detected
    "ANN101",  # Missing type annotation for `self` in method
    "EM102",  # Exception must not use an f-string literal, assign to variable first
    "TRY003",  # Avoid specifying long messages outside the exception class
]
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
